name: proyecto_tesis
description: "proyecto_tesis"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  intl: ^0.17.0
  http:
  provider:
  flutter_spinkit:
  flutter_bloc: ^7.0.0
  rxdart: ^0.27.3
  image_picker: ^0.8.4
  shared_preferences: ^2.0.8
  jwt_decode: ^0.3.1
  charts_flutter: ^0.12.0
  fl_chart: ^0.36.0
  geolocator: ^7.7.0
  flutter_speech: 2.0.0
  permission_handler: ^11.3.1
  geocoding:
  image: ^3.0.8
  path_provider: ^2.0.9
  fuzzy: ^0.5.1
  flutter_background_service: ^5.0.5
  url_launcher: ^6.0.9
  sensors_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SFProText
      fonts:
        - asset: fonts/FontsFree-Net-SFProText-Bold-1.ttf
        - asset: fonts/fonnts.com-SF_Pro_Text_Regular.ttf
        - asset: fonts/FontsFree-Net-SFProText-Medium-1.ttf
          weight: 700
